### ISSUE TITLE
Problem with Route_Sender

### ISSUE THREAD

**Issue by DerouineauNicolas** [haudiobe/ATSC_ROUTE#15]
Hello,
I checked out the ATSC_ROUTE project and followed the instructions in the README. I copied the Work directory in my apache2 /var/www/html/ folder.
I launch the sender through the UI http://127.0.0.1/Work/Route_Sender/bin/Sender_UI/ and I try to use the Receiver through http://127.0.0.1/Work/Route_Receiver/Receiver/. But it seems that no packets are being sent.

I see that the sender is launched through the sudo nice --20 ./Start2.sh 1000 command in the Route_Sender/bin/ folder. So I used this command directly in the terminal to see what is going wrong and I get the following message:

Converting MPD
2017-10-02T16:49:34.2466
../StaticToDynamic.php
PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "MultiRate.mpd" in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 71

Warning: simplexml_load_file(): I/O warning : failed to load external entity "MultiRate.mpd" in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 71
Failed loading XML file/var/www/html/Work/Route_Sender/bin
2017-10-02T16:49:34.2924
../StaticToDynamic.php
PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "MultiRate.mpd" in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 71

Warning: simplexml_load_file(): I/O warning : failed to load external entity "MultiRate.mpd" in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 71
Failed loading XML file/var/www/html/Work/Route_Sender/bin
Done
flute_sender: no process found
Opening Log File
Error: Elysium_1_0/efdt_MPD.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: Elysium_1_0/efdt_Video.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: Elysium_1_0/efdt_Audio.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: ToS_1_0/efdt_MPD.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: ToS_1_0/efdt_Video.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: ToS_1_0/efdt_Audio.xml is not valid file name
Total bytes sent: 0
Closing Log File

Any help on this issue would be really appreciated.

**Comment by waqarz** [comment]
PR https://github.com/waqarz/ATSC_ROUTE/pull/11 has really broken some things, regression from https://github.com/waqarz/ATSC_ROUTE/tree/ea756362c90a172ac9331d23687e287c707865d2

**Comment by waqarz** [comment]
![image](https://user-images.githubusercontent.com/3089913/31342274-864e73a6-ad0c-11e7-9b8a-4f3016a30fc2.png)
@AdithyanIlangovan Please take a look here, the feature on the left in red was there from where you forked, but was deleted in PR; how could this be?
![image](https://user-images.githubusercontent.com/3089913/31342908-612c37c8-ad0e-11e7-9924-f54013705936.png)

please check and also if there are any other related issues?

**Comment by waqarz** [comment]
@DerouineauNicolas this was addressed in https://github.com/waqarz/ATSC_ROUTE/pull/13 that I just now merged, this should fix this issue.

**Comment by DerouineauNicolas** [comment]
Hi waqarz, 
Thank you for your help. I checked out a04612c9e3dc47e138073eaa5366779697da1ad7.
Using the previous command (ie: sudo nice --20 ./Start2.sh 1000), I get the following errors:

genStsid.php
PHP Warning:  DOMDocument::save(Elysium_1_0/S-TSID.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(Elysium_1_0/usbd.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 54
genStsid.php
PHP Warning:  DOMDocument::save(ToS_1_0/S-TSID.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(ToS_1_0/usbd.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 54
Converting MPD
./ConvertMPD.sh: line 22: cd: Elysium_1_0: No such file or directory
2017-10-09T14:58:16.7220
Could not open input file: ../StaticToDynamic.php
./ConvertMPD.sh: line 46: cd: OLDPWD not set
./ConvertMPD.sh: line 22: cd: ToS_1_0: No such file or directory
2017-10-09T14:58:16.7599
Could not open input file: ../StaticToDynamic.php
./ConvertMPD.sh: line 46: cd: OLDPWD not set
chmod: cannot access 'Elysium_1_0/*': No such file or directory
chmod: cannot access 'ToS_1_0/*': No such file or directory
Done
flute_sender: no process found
Opening Log File
Opening Log File
Error: Elysium_1_0/efdt_MPD.xml is not valid file name
Error: Elysium_1_0/efdt_Video.xml is not valid file name
Total bytes sent: 0
Total bytes sent: 0
Closing Log File
Closing Log File
Opening Log File
Error: Elysium_1_0/efdt_Audio.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Opening Log File
Error: ToS_1_0/efdt_Video.xml is not valid file name
Error: ToS_1_0/efdt_MPD.xml is not valid file name
Total bytes sent: 0
Total bytes sent: 0
Closing Log File
Closing Log File
Opening Log File
Error: ToS_1_0/efdt_Audio.xml is not valid file name
Total bytes sent: 0
Closing Log File

**Comment by waqarz** [comment]
I dont see this comment, then I assume it is resolved;

**Comment by DerouineauNicolas** [comment]
I noticed that the arguments for the Start2.sh script have changed after posting my previous comment so I deleted it. Sorry about that.

Well actually, I'm still having some problems. It seems that the Sender UI is not able to detect my network interface (see the picture below)
![screenshot from 2017-10-10 11-51-55](https://user-images.githubusercontent.com/22216508/31380267-1e9e8dea-adb1-11e7-9679-22078407cb74.png

So once again, I try to use the Start2.sh script directly with:
sudo nice --20 ./Start2.sh 1000 127.0.0.1

I'm not sure which IP adress I should set there so I tried the localhost. I get the same errors as in my previous comment:

genStsid.php
PHP Warning:  DOMDocument::save(Elysium_1_0/S-TSID.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(Elysium_1_0/usbd.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 54
genStsid.php
PHP Warning:  DOMDocument::save(ToS_1_0/S-TSID.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(ToS_1_0/usbd.xml): failed to open stream: No such file or directory in /home/nicolas/prog/ATSC_ROUTE/Work/Route_Sender/bin/genStsid.php on line 54
Converting MPD
./ConvertMPD.sh: line 22: cd: Elysium_1_0: No such file or directory
2017-10-10T10:01:10.3901
Could not open input file: ../StaticToDynamic.php
./ConvertMPD.sh: line 46: cd: OLDPWD not set
./ConvertMPD.sh: line 22: cd: ToS_1_0: No such file or directory
2017-10-10T10:01:10.4286
Could not open input file: ../StaticToDynamic.php
./ConvertMPD.sh: line 46: cd: OLDPWD not set
chmod: cannot access 'Elysium_1_0/*': No such file or directory
chmod: cannot access 'ToS_1_0/*': No such file or directory
Done
flute_sender: no process found
Opening Log File
Error: Elysium_1_0/efdt_MPD.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Opening Log File
Error: Elysium_1_0/efdt_Audio.xml is not valid file name
Total bytes sent: 0
Closing Log File
Error: Elysium_1_0/efdt_Video.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Opening Log File
Error: ToS_1_0/efdt_MPD.xml is not valid file name
Total bytes sent: 0
Closing Log File
Opening Log File
Error: ToS_1_0/efdt_Audio.xml is not valid file name
Error: ToS_1_0/efdt_Video.xml is not valid file name
Total bytes sent: 0
Closing Log File
Total bytes sent: 0
Closing Log File
