### ISSUE TITLE
Content not displayed in receiver

### ISSUE THREAD

**Issue by DerouineauNicolas** [haudiobe/ATSC_ROUTE#19]
Hello,
I solved my Ethernet detection problem and I'm now using ATSC_ROUTE under Ubuntu 16.04. Running the last version of the code, I'm watching the /var/log/apache2/error.log file to detect problems on the Sender Side. When I click on the "on" button in the Sender UI, I can see the following message in error.log.

```
Start2.sh: no process found 
flute_sender: no process found
PHP Warning:  DOMDocument::save(Elysium_1_0/S-TSID.xml): failed to open stream: No such file or directory in /var/www/html/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(Elysium_1_0/usbd.xml): failed to open stream: No such file or directory in /var/www/html/Work/Route_Sender/bin/genStsid.php on line 54
PHP Warning:  DOMDocument::save(ToS_1_0/S-TSID.xml): failed to open stream: No such file or directory in /var/www/html/Work/Route_Sender/bin/genStsid.php on line 34
PHP Warning:  DOMDocument::save(ToS_1_0/usbd.xml): failed to open stream: No such file or directory in /var/www/html/Work/Route_Sender/bin/genStsid.php on line 54
./ConvertMPD.sh: line 22: cd: Elysium_1_0: No such file or directory
./ConvertMPD.sh: line 46: cd: OLDPWD not set
./ConvertMPD.sh: line 22: cd: ToS_1_0: No such file or directory
./ConvertMPD.sh: line 46: cd: OLDPWD not set
chmod: cannot access 'Elysium_1_0/*': No such file or directory
chmod: cannot access 'ToS_1_0/*': No such file or directory
flute_sender: no process found 
```

On the receiver side, I can see some "objects" in Dash_Content1: 
```
ls /var/www/html/Work/Route_Receiver/bin/Dash_Content1

object_0aCjwL  object_AHotl7  object_btsZ8Z  object_cJCCpv  object_DTQu3s  object_izBwY6  object_jEt44C  object_KiYi8b  object_y8WztL  object_yLjgjP
```

But the UI is stuck on "Tuning in ..." message

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas  I have a rough idea what the problem might be. I will take a look when I am back to work tomorrow morning.

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas Could you pull in the new version and retry this again? 
Let me know if it already works you.

The media contents were somehow gone missing because of one of the PR. I have added them back again.

**Comment by DerouineauNicolas** [comment]
Hi @AdithyanIlangovan,
I pulled the new version. I still get several error message:

    [Thu Oct 26 12:57:20.702096 2017] [mpm_prefork:notice] [pid 10536] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
    [Thu Oct 26 12:57:20.702165 2017] [core:notice] [pid 10536] AH00094: Command line: '/usr/sbin/apache2'
    Start2.sh: no process found
    flute_sender: no process found
    flute_sender: no process found
    [Thu Oct 26 12:57:40.007551 2017] [:error] [pid 10579] [client ::1:46496] PHP Warning:  file_get_contents(RcvConfig.txt): failed to open stream: No such file or directory in /var/www/html/Work/Route_Receiver/Receiver/index.php on line 274
    flute: no process found

    waiting to receive message
    received 490 bytes from ('*.*.*.*', 54076)
    <SLT bsid="1">
      <service hidden="true" majorChannelNo="1" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4005" slsProtocol="1" slsSourceIpAddress="*.*.*.*" tsi="5"/>
      </service>
      <service hidden="true" majorChannelNo="2" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4006" slsProtocol="1" slsSourceIpAddress="*.*.*.*" tsi="6"/>
      </service>
    </SLT>

    [Thu Oct 26 12:57:40.321401 2017] [:error] [pid 10579] [client ::1:46496] PHP Warning:  chdir(): No such file or directory (errno 2) in /var/www/html/Work/Route_Receiver/Receiver/ReceiverConfig/onloadfunc.php on line 17, referer: http://localhost/Work/Route_Receiver/Receiver/
    python: can't open file 'readFromSLT.py': [Errno 2] No such file or directory
    [Thu Oct 26 12:57:42.203706 2017] [:error] [pid 10580] [client ::1:46500] PHP Warning:  file_get_contents(RcvConfig.txt): failed to open stream: No such file or directory in /var/www/html/Work/Route_Receiver/Receiver/Process.php on line 13, referer:http://localhost/Work/Route_Receiver/Receiver/
    flute: no process found
    flute: no process found
    ./flute: /usr/local/lib/libcurl.so.4: no version information available (required by ./flute)
    ./flute: /lib/x86_64-linux-gnu/libssl.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)
    ./flute: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)

Should I recompile your flute library to link it against non-debug libssl ?

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas  Yes. Please try that. I am guessing the problem is because of the mismatches in the version of libssl. I remember seeing this before. 
Can you check your libssl version?

Also, run the make command from the **Route Receiver** folder to make sure that it is recompiled

**Comment by waqarz** [comment]
@AdithyanIlangovan, @DerouineauNicolas

I see that ssl may have an issue, but there are still more issues before that that should not be:

    [Thu Oct 26 12:57:20.702096 2017] [mpm_prefork:notice] [pid 10536] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
    [Thu Oct 26 12:57:20.702165 2017] [core:notice] [pid 10536] AH00094: Command line: '/usr/sbin/apache2'
    Start2.sh: no process found
    flute_sender: no process found
    flute_sender: no process found

This (above) is fine

    [Thu Oct 26 12:57:40.007551 2017] [:error] [pid 10579] [client ::1:46496] PHP Warning:  file_get_contents(RcvConfig.txt): failed to open stream: No such file or directory in /var/www/html/Work/Route_Receiver/Receiver/index.php on line 274

This (above) is an issue

    flute: no process found

    waiting to receive message
    received 490 bytes from ('*.*.*.*', 54076)
    <SLT bsid="1">
      <service hidden="true" majorChannelNo="1" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4005" slsProtocol="1" slsSourceIpAddress="*.*.*.*" tsi="5"/>
      </service>
      <service hidden="true" majorChannelNo="2" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4006" slsProtocol="1" slsSourceIpAddress="*.*.*.*" tsi="6"/>
      </service>
    </SLT>

    [Thu Oct 26 12:57:40.321401 2017] [:error] [pid 10579] [client ::1:46496] PHP Warning:  chdir(): No such file or directory (errno 2) in /var/www/html/Work/Route_Receiver/Receiver/ReceiverConfig/onloadfunc.php on line 17, referer: http://localhost/Work/Route_Receiver/Receiver/

This (above) is also an issue

    python: can't open file 'readFromSLT.py': [Errno 2] No such file or directory

This (above) is also an issue

    [Thu Oct 26 12:57:42.203706 2017] [:error] [pid 10580] [client ::1:46500] PHP Warning:  file_get_contents(RcvConfig.txt): failed to open stream: No such file or directory in /var/www/html/Work/Route_Receiver/Receiver/Process.php on line 13, referer:http://localhost/Work/Route_Receiver/Receiver/

This (above) is also an issue

    flute: no process found
    flute: no process found
    ./flute: /usr/local/lib/libcurl.so.4: no version information available (required by ./flute)
    ./flute: /lib/x86_64-linux-gnu/libssl.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)
    ./flute: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)

I think there is a common issue that results in complaints of not finding files and paths, and this is not related to making the code. If you are using the same platform (Ubuntu 16 64 bit), you should not need to recompile the binary (which may end up in more issues)

**Comment by DerouineauNicolas** [comment]
I'm using openssl version provided with Ubuntu 16.04:
OpenSSL> version
OpenSSL 1.0.2g  1 Mar 2016

By default, it's installed in:
/lib/x86_64-linux-gnu/libssl.so.1.0.0

I created a symbolic link /lib/x86_64-linux-gnu/libssl.so.1.0.2 linking to the file above.

Ps: I got rid of the following error message by reinstalling properly openssl:
    ./flute: /usr/local/lib/libcurl.so.4: no version information available (required by ./flute)

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas Interesting. Later, I will setup a fresh clone of the repo and see whether I am able to run from the beginning.

In the meantime, could you please check if the files specified as missing are present in the directory in your repo?

**Comment by DerouineauNicolas** [comment]
Changing the directory at line 17 in /var/www/html/Work/Route_Receiver/Receiver/ReceiverConfig/onloadfunc.php from 

    chdir('../Receiver/SLT_signalling'); 
to
    chdir('../SLT_signalling');

seems to fix the issue for the chdir.

RcvConfig.txt is not found in my repo.

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas There were couple of minor bugs which I fixed and pushed to the latest repo.
I setup a fresh clone in a new ubuntu PC. I was able to run the whole thing now.

I just faced two issues : 

1. I had to install a python dependency. Like so 
`sudo apt-get install python-lxml`

2. In Sender/Sender_UI/trafficFilter.php file, I had to change 

```
<?php

ini_set('memory_limit','-1');//remove memory limit
exec("sudo tc qdisc delete dev eth0 root");
exec("sudo tc qdisc add dev eth0 root handle 1: cbq avpkt 1000 bandwidth 5000mbit");
exec("sudo tc class add dev eth0 parent 1: classid 1:1 cbq rate 35000kbit allot 1500 prio 5 bounded isolated");
exec("sudo tc filter add dev eth0 parent 1: protocol ip prio 16 u32 match ip dst 224.1.1.1 flowid 1:1");

echo "Done setting traffic pattern!";

?>
```

the eth0 to network interface that I had. In my case it was enp5s0. These were the only two fixes that were required. 

I would recommend that you pull in the latest version or clone a new copy and try it out. If you still face issues, let me know.

**Comment by DerouineauNicolas** [comment]
@AdithyanIlangovan 
I pulled the last version. I'm still getting the following error messages:

    [Fri Nov 03 12:27:13.168474 2017] [core:notice] [pid 12640] AH00094: Command line: '/usr/sbin/apache2'
    Start2.sh: no process found
    flute_sender: no process found
    PHP Warning:  unlink(FluteInput_Video.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 388
    PHP Warning:  unlink(FluteInput_Audio.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 389
    PHP Warning:  unlink(FluteInput_MPD.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 460
    PHP Warning:  unlink(FluteInput_Video.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 388
    PHP Warning:  unlink(FluteInput_Audio.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 389
    PHP Warning:  unlink(FluteInput_MPD.txt): No such file or directory in /var/www/html/Work/Route_Sender/bin/StaticToDynamic.php on line 460
    flute_sender: no process found
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    ./flute_sender: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute_sender)
    flute: no process found

    waiting to receive message
    received 490 bytes from ('MyIP', 58029)
    <SLT bsid="1">
      <service hidden="true" majorChannelNo="1" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4005" slsProtocol="1" slsSourceIpAddress="MyIP" tsi="5"/>
      </service>
      <service hidden="true" majorChannelNo="2" serviceCategory="1">
        <broadcastSvcSignalling slsDestinationIpAddress="224.1.1.1" slsDestinationUdpPort="4006" slsProtocol="1" slsSourceIpAddress="MyIP" tsi="6"/>
     </service>
    </SLT>

    [Fri Nov 03 12:28:24.925405 2017] [:error] [pid 12645] [client ::1:36758] PHP Warning:  unlink(../bin/timelog.txt): No such file or directory in /var/www/html/Work/Route_Receiver/Receiver/Process.php on line 5, referer: http://localhost/Work/Route_Receiver/Receiver/
    flute: no process found
    flute: no process found
    ./flute: /lib/x86_64-linux-gnu/libssl.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)
    ./flute: /lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./flute)

One thing is also strange. I see udp packets in wireshark for LLS of the SLT (ie: MyIP->224.0.23.60), but I can't see packets for the channels traffic (MyIP->224.1.1.1)

**Comment by AdithyanIlangovan** [comment]
@DerouineauNicolas Did you try fixing the libssl like you mentioned earlier?

**Comment by AdithyanIlangovan** [comment]
In case you have a problem with libcrypto.so saying that libcrypto.so.1.0.2 not found, you can add this repository and install the required version:
```
sudo apt-get update
sudo apt-add-repository ppa:ondrej/apache2
sudo apt-get install libssl1.0.2 libssl1.0.2-doc
```

**Comment by AdithyanIlangovan** [comment]
Also, which libcur version you are using?
For libcurl library, I installed: libcurl3 and libcurl3-gnutls

**Comment by DerouineauNicolas** [comment]
@AdithyanIlangovan your trick with the ppa did the job, I'm now able to tune in on the two channels in my browser. Thank you very much for your help !

**Comment by AdithyanIlangovan** [comment]
That is great @DerouineauNicolas ! Good to know :)
